### ISSUE TITLE
Error when generate sign APK

### ISSUE THREAD

**Issue by kokorambo** [techery/progresshint#12]
Hi techery, I have used your lib to build my project. When I run project in android studio, it ok but when I generated apk, it's get error
Error:Error: Unexpected cast to SeekBarHintDelegateHolder: layout tag was io.techery.progresshint.addition.widget.SeekBar [WrongViewCast]
Here is my code 
        ProgressHintDelegate.SeekBarHintDelegateHolder seekBar = (ProgressHintDelegate.SeekBarHintDelegateHolder) findViewById(R.id.seekbar_point);
        seekBar.getHintDelegate()
                .setHintAdapter(new ProgressHintDelegate.SeekBarHintAdapter() {
                    @Override
                    public String getHint(android.widget.SeekBar seekBar, int progress) {
                        return String.valueOf(6969);
                    }
                });
        SeekBar seekBar1 = (SeekBar) findViewById(R.id.seekbar_point);
        seekBar1.setProgress(6969);
        seekBar1.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View view, MotionEvent motionEvent) {
                return true;
            }
        })
Can you help me to fix this?

**Comment by almozavr** [comment]
Hi! What's your xml? And build.gradle with dependencies.
P.S. please, use markdown formatting for code snippets.

**Comment by kokorambo** [comment]
I have solved my problem. Replace ProgressHintDelegate.SeekBarHintDelegateHolder to Seekbar make it run perfectly. Thanks a lot for your support :D
