### ISSUE TITLE
popup starts from the left (RTL support)

### ISSUE THREAD

**Issue by alidabour** [techery/progresshint#13]
I tried to use it with arabic app (RTL) but popup starts from the left (Expected to start from the right)

**Comment by almozavr** [comment]
@alidabour I've checked the android's `Seekbar` which progresshint is massively based on, and it looks like it doesn't support RTL as well (( 
One thing I could suggest is to use custom `SeekBarHintAdapter` and reverse the value (aka 100-progress) and start with 100.

```java
seekbar.getHintDelegate().setHintAdapter(new SeekBarHintAdapter() {
          @Override public String getHint(android.widget.SeekBar seekBar, int progress) {
            return String.valueOf(100-progress);
          }
        });
seekbar.setProgress(100);
```

I know, it's not a real solution, but progress hint lib can't take responsibility of widgets which it's applied to.
