### ISSUE TITLE
In 7.1.1 has  quesiton  

### ISSUE THREAD

**Issue by 287138531** [techery/progresshint#14]
![qq 20180302172235](https://user-images.githubusercontent.com/13412535/36892028-760c3afc-1e3e-11e8-96bb-a77e01b7c8cd.jpg)

can't see the label

**Comment by almozavr** [comment]
Provide more details about device, maybe logs, etc

**Comment by 287138531** [comment]
![screenshot_20180302-174544](https://user-images.githubusercontent.com/13412535/36893102-cd6b4966-1e41-11e8-8253-e91692018238.jpg)

**Comment by almozavr** [comment]
From what I see from screenshot and device data -> seems like custom theme on H2OS firmware breaks android defaults for PopupWindow. Please, try set up custom layout for popup with fixed height
