### ISSUE TITLE
In verticalseekbar how to show hint on left side

### ISSUE THREAD

**Issue by aakashy85** [techery/progresshint#16]
In verticalseekbar how to show hint popup on left side.

**Comment by almozavr** [comment]
Unsupported, and would be tricky due to nature of `PopupWindow` which is used underneath, see https://github.com/techery/progresshint/blob/3d40fe602e931eb12ebd876c23520844795617ee/library/src/main/java/io/techery/progresshint/ProgressHintDelegate.java#L161

**Comment by almozavr** [comment]
You hack behaviour with negative offset, e.g. `app:popupOffset="-100dp"`

**Comment by aakashy85** [comment]
Its working Thanks
