### ISSUE TITLE
How to set progressbar background image.?

### ISSUE THREAD

**Issue by aakashy85** [techery/progresshint#17]
I am using this layout.....

<com.h6ah4i.android.widget.verticalseekbar.VerticalSeekBarWrapper
                        android:id="@+id/seekbar"
                        android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:layout_marginBottom="@dimen/dimen_32"
                        android:layout_marginLeft="@dimen/dimen_2"
                        android:layout_marginTop="@dimen/dimen_8">
    <io.techery.progresshint.addition.widget.VerticalSeekBar
                            android:id="@+id/seekbar_vertical"
                            style="@style/tallerBarStyle"
                            android:layout_width="0dp"
                            android:layout_height="0dp"
                            android:layout_marginTop="@dimen/dimen_10"
                            android:max="10"
                            android:progressDrawable="@drawable/nvs_rating_metter"
                            android:thumb="@drawable/seek"
                            android:thumbOffset="@dimen/dimen_3"
                            app:popupAlwaysShown="true"
                            app:popupLayout="@layout/custom_progress_hint_popup"
                            app:popupStyle="follow"
                            app:seekBarRotation="CW270"
                            app:tickMarkTint="@color/purple_color" />
                        
                    </com.h6ah4i.android.widget.verticalseekbar.VerticalSeekBarWrapper>

Look like this.
![screenshot_20180308-154038](https://user-images.githubusercontent.com/25077436/37145635-5d151200-22e7-11e8-8d42-2f05675ae94c.png)

**Comment by almozavr** [comment]
`VerticalSeekBar` is extension for https://github.com/h6ah4i/android-verticalseekbar -> refer to this library for further explanations.
