### ISSUE TITLE
How to add a custom layout text

### ISSUE THREAD

**Issue by Cosminnv** [techery/progresshint#22]
Can anyone show a sample of how to add a custom layout in the text bubble?
I tried creating a layout with a TextView with id/text1 but it gives me "setText on NullPointerException".

**Comment by almozavr** [comment]
@Cosminnv you're right, you have to include `TextView` with `android:id/text1`. Also you could set a custom value via `SeekBarHintAdapter`.
See the sample app: 
- https://github.com/techery/progresshint/blob/master/sample/src/main/res/layout/custom_progress_hint_popup.xml
- https://github.com/techery/progresshint/blob/master/sample/src/main/java/com/example/progresshint/MainActivity.java#L35
