### ISSUE TITLE
HintBox overlaps everything

### ISSUE THREAD

**Issue by Cosminnv** [techery/progresshint#23]
![Screenshot_1573725655](https://user-images.githubusercontent.com/48117967/68846926-198e3080-06ce-11ea-8298-035bf54afa91.png)

I added a custom Hintbox but now it overlaps everything. 
This is my custom hintbox:

`<?xml version="1.0" encoding="UTF-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:elevation="1dp"
    android:paddingEnd="5dp">

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/black_baloon"
        android:gravity="center"
        android:orientation="vertical">
    <TextView
        android:id="@android:id/text1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:ellipsize="end"
        android:gravity="center"
        android:singleLine="true"
        android:textStyle="bold"
        android:textColor="@color/colorWhite"
        android:textSize="24sp"
        android:layout_marginTop="10dp" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="14sp"
        android:textColor="@color/colorWhite"
        android:text="MIN/SETT"/>
    </LinearLayout>
</RelativeLayout>`

Any solutions?

**Comment by almozavr** [comment]
If you're inside the `ScrollView/RecyclerView` use `ProgressHintScrollController`. README holds a link to the sample. Otherwise, this is intended behavior as the view behind the scene is the `PopupWindow`
