### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by Calagahn** [techery/progresshint#24]
Hi there,

I know there hasn't been activity on this project since a long time, however, for those like me still using this library, I've noticed that the dependencies for "library-addition" on "jitpack.io" are broken.
Consequence is that it is not possible to build a project using **progresshint** anymore without getting an error such as :

`Could not find library-addition-0.4.1.aar (com.github.techery.progresshint:library-addition:0.4.1)`

It seems the "library-addition" directory has just been removed.
It would be great if this library can stay available "as it is" (yeah, lazy mode, I know).

Thanks in advance for the support.

**Comment by almozavr** [comment]
Build is now up and running, tested with latest release. Cheers 🙌
```
implementation "com.github.techery.progresshint:library-addition:0.4.2"
```
