### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rajtrada** [techery/progresshint#5]
I am not able to add this in my project. I am getting bellow error:

Error:(31, 13) Failed to resolve: com.github.techery.progresshint:library-addition:{jitpack-debug}
<a href="openFile:/Users/home/AndroidStudioProjects/MyApplication/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

I am using Android Studio ver 2.1 and gradle version 2.1.0

**Comment by kalpesh-lakhani** [comment]
i am facing the same issue. is there any solution for make it working ?

Thanks in Advance.

**Comment by almozavr** [comment]
{jitpack-debug} should be replaced with latest version, it's latest tag and could be seen on the Jitpack badge. Latest version is 0.2.3

**Comment by rajtrada** [comment]
Thanks for your reply,

Now I am getting Error:Module 'com.github.techery:progresshint:0.2.3' depends on one or more Android Libraries but is a jar

My gradle is as bellow :

apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion '23.0.3'

```
defaultConfig {
    applicationId "com.example.test.myapplication"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

repositories {
    jcenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.github.techery:progresshint:0.2.3'
}

**Comment by almozavr** [comment]
`compile 'com.github.techery.progresshint:library:0.2.3@aar'`
or
`compile 'com.github.techery.progresshint:library-addition:0.2.3'`

**Comment by rajtrada** [comment]
Thanks,

It is working now.
