### ISSUE TITLE
Set Min Max value

### ISSUE THREAD

**Issue by rajtrada** [techery/progresshint#6]
How I can set one slider with range from 100 to 900 and another with 1 to 5.

**Comment by kalpesh-lakhani** [comment]
I am facing same issue. anyone has the solution for the same ?
Thanks in advance.

**Comment by almozavr** [comment]
@rajtrada do you mean floating hint value? 
2 ways:
- Using HintAdapter

``` java
seekBar.getHintDelegate()
    .setHintAdapter(new SeekBarHintAdapter() {
      @Override public String getHint(android.widget.SeekBar seekBar, int progress) {
        return String.valueOf(progress*multiplexor);
      }
    }); 
```
- Via SeekBar itself.

**Comment by rajtrada** [comment]
@@It is not working for me because I want to set progress from 0 to 900, if I set like this I am getting each value in multiple of 9 like 0, 9, 18....900 but I want all value between 0 to 900 like 0,1,2,3...900

**Comment by almozavr** [comment]
Again, it's up to `SeekBar` to define progress rules.
https://developer.android.com/reference/android/widget/ProgressBar.html#setMax(int)

**Comment by rajtrada** [comment]
Thanks
