### ISSUE TITLE
Popup position issue

### ISSUE THREAD

**Issue by aarambhin** [techery/progresshint#7]
If I set seekBarRotation to CW270 then popup not display properly at bottom end of slider you can check that in attached image

![screenshot_2016-05-24-13-29-38](https://cloud.githubusercontent.com/assets/9485392/15750460/2b2c6a1a-2904-11e6-9131-1fea9a0abd46.png)

**Comment by almozavr** [comment]
[VerticalSeekBar](https://github.com/h6ah4i/android-verticalseekbar) calculations are tricky due to it's nature of "hacky" widget. Calculations are done via `VerticalProgressHintDelegate` – you can debug here  and check your particular case issue.

**Comment by aarambhin** [comment]
Hi Thanks for reply,

I think you are not getting what I am trying to say, I am trying to say that popup is not displayed at proper position it is bellow sider not at track position. You can see that in image "1" is displayed in bottom bar not with track bar.

**Comment by almozavr** [comment]
It’s clear. The root problem is exact I described above.

**Comment by aarambhin** [comment]
Is there any way to hide popup ?

**Comment by almozavr** [comment]
fixed with 0.2.4 release
